### ISSUE TITLE
Upload for sections raise AttributeError

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#12]
This line in particular:         `for comment in submission.submission_comments:`

I think the two different API-calls (assignment.get_submissions and section.get_multiple_submissions) might return different objects.

If the AttributeError for submission_comments is caught, another AttributeError is raised, for a mission courseid attribute in the Submission-object.

Not sure how helpful this is, but the output + stacktrace follows:
(I knew the gradings where not duplicates, so it seemed safe enough to just catch and ignore the first exception, hence the output-print).

```
Prepare upload for section Hold 10 Dat; - 42564 (90343)
Uploading feedback to: 2i (103858)
Sure? (y/n) : y
Submit: user_id=XXXX, grade=1
Exception caught when checking if duplicate
Uploading new feedback: 8488
Traceback (most recent call last):
  File "../../staffeli_nt/staffeli_nt/upload.py", line 174, in <module>
    grade(
  File "../../staffeli_nt/staffeli_nt/upload.py", line 52, in grade
    submission.upload_comment(f_path)
  File "/Users/Mads/Documents/diku/instruktor/staffelitest/lib/python3.8/site-packages/canvasapi/submission.py", line 163, in upload_comment
    self.course_id, self.assignment_id, self.user_id
  File "/Users/Mads/Documents/diku/instruktor/staffelitest/lib/python3.8/site-packages/canvasapi/canvas_object.py", line 17, in __getattribute__
    return super(CanvasObject, self).__getattribute__(name)
AttributeError: 'Submission' object has no attribute 'course_id'
```

**Comment by kfl** [comment]
That's strange. 

I have changed `upload.py` to be more like `upload_single.py`, the later seems to work. Also I have added the flag `--warn-missing` to check that all students in a section has been graded.

**Comment by kfl** [comment]
Hmm, something is still wrong.

**Comment by kfl** [comment]
It should work now. At least it seems to Work For Me:tm: :wink:

@madsobitsoe can you check if it works for you?

**Comment by madsobitsoe** [comment]
That is the most popular metric ;) 
I will test as soon as I'm done grading this week. 
It would be nice to have a mock-course on absalon for testing. Is that do-able or is it out-of-reach?

**Comment by kfl** [comment]
I can make a test course on Absalon, and invite you as student or TA. However, it usually works best if we are three people (to try out different combinations). It there a suitable candidate amongst the PoP TAs or should I try to solicit one from AP?

**Comment by Munksgaard** [comment]
I can help, what do you need me to do?

**Comment by kfl** [comment]
I have invited you, @madsobitsoe and @Munksgaard, to a test course at Absalon.

@madsobitsoe I suggest that you set up an assignment so that @Munksgaard can hand in something and you can grade him.

**Comment by madsobitsoe** [comment]
I have made two assignments - one individual and one group. 
I also created a group set and added @Munksgaard to the only group in it. 
@kfl can you add a section in the test-course?

**Comment by Munksgaard** [comment]
Should I upload something?

**Comment by madsobitsoe** [comment]
Yes. Just some random file should do. :)

**Comment by Munksgaard** [comment]
Done

**Comment by kfl** [comment]
There are now three sections:

* Good students (only @Munksgaard so far)
* Bad students (only @afilinski because I don't expect him hand in anything more)
* Everybody, well everybody
